# Quick notes on ImmPort dataset SDY2011 (2025-12-30)

After exploring with the ImmPort API using different endpoints, it appears that there is no available Olink data for this study. Only CyTOF data is available.

Since I don't have tools to work with CyTOF data at the moment, I will pause further exploration of this dataset for now. 
Try another study to find Olink data.

# Objective

We have successfully downloaded datasets from ImmPort using Method 2 and Method 3 by following the tutorial (`immport-datasets.ipynb`).

Now, I have a target study which has flow cytometry data and Olink data that I want to download for analysis: **SDY2011**.
Try to use Method 3 to explore and download datasets from this study.

In [1]:
import sys
import os
import pandas as pd

# Set the Python path to the location of the directory containing "immport_download.py"
immport_download_code = "../../immport-data-download-tool/bin/" # Adjust this path as needed
sys.path.insert(0,immport_download_code)
os.chdir(immport_download_code)

import immport_download

In [2]:
# Configure parameters
user_name = input("ImmPort Username: ")
password = input("ImmPort Password: ")
download_directory = "../../output" # Note: Avoid using parent paths with spaces to prevent potential issues
data_directory = "../../data"

# Mthod 3: Download datasets from a target study (SDY2011) using ImmPort API

In [3]:
# Method 3

target_study = "SDY2011"
# target_study = "SDY202"

In [4]:
# Request a token, then make API call, then load into Pandas's DataFrame
token = immport_download.request_immport_token(user_name, password)

In [14]:
f"https://api.immport.org/data/query/result/hai?studyAccession={target_study}"

'https://api.immport.org/data/query/result/hai?studyAccession=SDY2011'

In [ ]:
# https://immport.org/data/query/swagger-ui/index.html#/

In [ ]:
# https://docs.immport.org/apidocumentation/shareddataapi/studyfilepaths/
# BASE URL = https://www.immport.org/data/query/api/study/

In [ ]:

r = immport_download.api(f"https://api.immport.org/data/query/result/hai?studyAccession={target_study}",token)
hai_results = pd.read_json(r)

/var/folders/s8/3jyy749s5dd02sr2jvqg53b40000gn/T/ipykernel_96121/3925602704.py:4: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  hai_results = pd.read_json(r)

In [18]:
hai_results.shape

(0, 0)

In [16]:
hai_results.columns

# No data because HAI data is not available for SDY2011
# Try to use Method 2 to download some files from SDY2011 for now.

RangeIndex(start=0, stop=0, step=1)

In [19]:
# ask the Study API what’s available

url = f"https://www.immport.org/data/query/api/study/file/{target_study}"
r = immport_download.api(url, token)
print(r[:500])

[ {
  "studyFileAccession" : "SFL22034",
  "studyAccession" : "SDY2011",
  "studyFileType" : "Study Data",
  "description" : "CyTOF fcs",
  "fileName" : "200422_HIMC15_PICR_MDIPA_Subj_089e98eaT1_debc.fcs",
  "filePath" : "/SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_Subj_089e98eaT1_debc.fcs"
},{
  "studyFileAccession" : "SFL22035",
  "studyAccession" : "SDY2011",
  "studyFileType" : "Study Data",
  "description" : "CyTOF fcs",
  "fileName" : "200422_HIMC15_PICR_MDIPA_Subj_29703e49T1_debc.fcs",

In [20]:
len(r)

55174

In [21]:
print(r[-500:])

: "Study Data",
  "description" : "Olink control samples metadata",
  "fileName" : "olink_36plt_20201030_ctrlsamples_meta.csv",
  "filePath" : "/SDY2011/StudyFiles/olink_36plt_20201030_ctrlsamples_meta.csv"
},{
  "studyFileAccession" : "SFL22381",
  "studyAccession" : "SDY2011",
  "studyFileType" : "Study Data",
  "description" : "Olink Data",
  "fileName" : "olink_36plt_202012_pt_meta_12052022_removed.csv",
  "filePath" : "/SDY2011/StudyFiles/olink_36plt_202012_pt_meta_12052022_removed.csv"
} ]

In [26]:
# fcsAnalyzed

# Request a token, then make API call, then load into Pandas's DataFrame
token = immport_download.request_immport_token(user_name, password)
r = immport_download.api(f"https://api.immport.org/data/query/result/fcsAnalyzed?studyAccession={target_study}",token)
results = pd.read_json(r)

/var/folders/s8/3jyy749s5dd02sr2jvqg53b40000gn/T/ipykernel_96121/2798507204.py:6: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  results = pd.read_json(r)

In [27]:
results.shape

(0, 0)

In [28]:
r = immport_download.api(
    f"https://www.immport.org/data/query/api/study/filePath/studyFiles/{target_study}",
    token
)
study_files = pd.read_json(r)
study_files.head()

/var/folders/s8/3jyy749s5dd02sr2jvqg53b40000gn/T/ipykernel_96121/2328002751.py:5: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  study_files = pd.read_json(r)

,fileDetailsId,generatedMD5,studyAccession,fileType,fileAccession,fileName,path
0,8253,3c7e8235b56c33ab75c34acddca1704e,SDY2011,study_file,SFL22381,olink_36plt_202012_pt_meta_12052022_removed.csv,SDY2011/StudyFiles/olink_36plt_202012_pt_meta_...
1,9871,ea63c7c3a48912ec0c9833337b7048f3,SDY2011,study_file,SFL22034,200422_HIMC15_PICR_MDIPA_Subj_089e98eaT1_debc.fcs,SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_Su...
2,9872,b3f5f088db723b389e7ee24ee4304bad,SDY2011,study_file,SFL22035,200422_HIMC15_PICR_MDIPA_Subj_29703e49T1_debc.fcs,SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_Su...
3,9873,51126349772009bb5c14534601d305b9,SDY2011,study_file,SFL22036,200422_HIMC15_PICR_MDIPA_Subj_2d3ac920T1_debc.fcs,SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_Su...
4,9874,18800883a566f8e86e63c3b8cad74a03,SDY2011,study_file,SFL22037,200422_HIMC15_PICR_MDIPA_Subj_34518e80T1_debc.fcs,SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_Su...

In [29]:
study_files.shape

(189, 7)

In [30]:
study_files.tail()

,fileDetailsId,generatedMD5,studyAccession,fileType,fileAccession,fileName,path
184,10277,4daa977610b2b9458ee767a2043a6382,SDY2011,study_file,SFL22217,200616_MDIPAa4_Subj_c06f90b7T4_debc.fcs,SDY2011/StudyFiles/200616_MDIPAa4_Subj_c06f90b...
185,10278,93b0a97dee7f2a9b68e12468290a3922,SDY2011,study_file,SFL22218,200616_MDIPAa4_Subj_c06f90b7T8_debc.fcs,SDY2011/StudyFiles/200616_MDIPAa4_Subj_c06f90b...
186,10279,fad0089ff02b14795f7b61b8b2572030,SDY2011,study_file,SFL22219,Chen_MBAA_Results.xlsx,SDY2011/StudyFiles/Chen_MBAA_Results.xlsx
187,10280,4aeb71732412f4ad10de6d7964184923,SDY2011,study_file,SFL22220,olink_36plt_202012_pt_meta.csv,SDY2011/StudyFiles/olink_36plt_202012_pt_meta.csv
188,10281,5e725714d3647103ccbe6843acb51c96,SDY2011,study_file,SFL22221,olink_36plt_20201030_ctrlsamples_meta.csv,SDY2011/StudyFiles/olink_36plt_20201030_ctrlsa...

In [ ]:
# study/studyfile/{studyAccession}

In [31]:
# Download "filePath" : "/SDY2011/StudyFiles/olink_36plt_20201030_ctrlsamples_meta.csv"

immport_download.download_file(user_name,password,
    "/SDY2011/StudyFiles/olink_36plt_20201030_ctrlsamples_meta.csv", download_directory
)

Completed: 18K bytes transferred in 0 seconds
 (243K bits/sec), in 1 file.

In [34]:
# Download "filePath" : "/SDY2011/StudyFiles/olink_36plt_202012_pt_meta.csv"

immport_download.download_file(user_name,password,
    "/SDY2011/StudyFiles/olink_36plt_202012_pt_meta.csv", download_directory
)

Completed: 576K bytes transferred in 0 seconds
 (6347K bits/sec), in 1 file.

In [35]:
# Download "filePath" : "/SDY2011/StudyFiles/olink_36plt_202012_pt_meta_12052022_removed.csv"

immport_download.download_file(user_name,password,
    "/SDY2011/StudyFiles/olink_36plt_202012_pt_meta_12052022_removed.csv", download_directory
)

Completed: 483K bytes transferred in 0 seconds
 (4946K bits/sec), in 1 file.

In [32]:
# Download "filePath" : "/SDY2011/StudyFiles/Chen_MBAA_Results.xlsx"

immport_download.download_file(user_name,password,
    "/SDY2011/StudyFiles/Chen_MBAA_Results.xlsx", download_directory
)

Completed: 8243K bytes transferred in 2 seconds
 (31977K bits/sec), in 1 file.

In [14]:

r = immport_download.api(f"https://api.immport.org/data/query/result/filePath?studyAccession={target_study}",token)
df = pd.read_json(r)
df.head()

/var/folders/s8/3jyy749s5dd02sr2jvqg53b40000gn/T/ipykernel_61701/3058520764.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(r)

,filePathId,fileInfoId,fileDetail,filesizeBytes,fileName,originalFileName,sourceType,sourceAccession,experimentAccession,measurementTechnique,...,strain,armAccession,armName,ageEvent,ageEventSpecify,ageUnit,maxSubjectAge,minSubjectAge,subjectPhenotype,filePath
0,916162_ES1674866_BS1227210,916162,CyTOF result,173358803,200604_PICR_MDIPAa4_C_Subj_03ca6bb0T1_MDIPAa4_...,200604_PICR_MDIPAa4_C_Subj_03ca6bb0T1_MDIPAa4_...,EXPSAMPLE,ES1674866,EXP34044,CyTOF,...,NaN,ARM6540,COVID positive,Age at enrollment,NaN,Years,89,18,NaN,/SDY2011/ResultFiles/CyTOF_result/200604_PICR_...
1,916163_ES1674867_BS1227211,916163,CyTOF result,101251246,200604_PICR_MDIPAa4_C_Subj_03ca6bb0T4_MDIPAa4_...,200604_PICR_MDIPAa4_C_Subj_03ca6bb0T4_MDIPAa4_...,EXPSAMPLE,ES1674867,EXP34044,CyTOF,...,NaN,ARM6540,COVID positive,Age at enrollment,NaN,Years,89,18,NaN,/SDY2011/ResultFiles/CyTOF_result/200604_PICR_...
2,916164_ES1674868_BS1227212,916164,CyTOF result,20113961,200529_HIMC15_MDIPAa4_Subj_05f57419T1_debc.916...,200529_HIMC15_MDIPAa4_Subj_05f57419T1_debc.fcs,EXPSAMPLE,ES1674868,EXP34044,CyTOF,...,NaN,ARM6540,COVID positive,Age at enrollment,NaN,Years,89,18,NaN,/SDY2011/ResultFiles/CyTOF_result/200529_HIMC1...
3,916165_ES1674869_BS1227213,916165,CyTOF result,57999091,200604_PICR_MDIPAa4_A_Subj_06f24a67T1_MDIPAa4_...,200604_PICR_MDIPAa4_A_Subj_06f24a67T1_MDIPAa4_...,EXPSAMPLE,ES1674869,EXP34044,CyTOF,...,NaN,ARM6540,COVID positive,Age at enrollment,NaN,Years,89,18,NaN,/SDY2011/ResultFiles/CyTOF_result/200604_PICR_...
4,916166_ES1674870_BS1227214,916166,CyTOF result,122689162,200604_PICR_MDIPAa4_A_Subj_06f24a67T12_MDIPAa4...,200604_PICR_MDIPAa4_A_Subj_06f24a67T12_MDIPAa4...,EXPSAMPLE,ES1674870,EXP34044,CyTOF,...,NaN,ARM6540,COVID positive,Age at enrollment,NaN,Years,89,18,NaN,/SDY2011/ResultFiles/CyTOF_result/200604_PICR_...

In [37]:
df.shape

(185, 37)

In [ ]:
print(df["experimentAccession"].unique())
print(df["measurementTechnique"].unique())

# Why there is only CyTOF data? Why no Olink data?

['EXP34044']
['CyTOF']

In [44]:
print(df["armName"].unique())

['COVID positive' 'COVID negative']

In [43]:
study_files.head()

,fileDetailsId,generatedMD5,studyAccession,fileType,fileAccession,fileName,path
0,8253,3c7e8235b56c33ab75c34acddca1704e,SDY2011,study_file,SFL22381,olink_36plt_202012_pt_meta_12052022_removed.csv,SDY2011/StudyFiles/olink_36plt_202012_pt_meta_...
1,9871,ea63c7c3a48912ec0c9833337b7048f3,SDY2011,study_file,SFL22034,200422_HIMC15_PICR_MDIPA_Subj_089e98eaT1_debc.fcs,SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_Su...
2,9872,b3f5f088db723b389e7ee24ee4304bad,SDY2011,study_file,SFL22035,200422_HIMC15_PICR_MDIPA_Subj_29703e49T1_debc.fcs,SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_Su...
3,9873,51126349772009bb5c14534601d305b9,SDY2011,study_file,SFL22036,200422_HIMC15_PICR_MDIPA_Subj_2d3ac920T1_debc.fcs,SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_Su...
4,9874,18800883a566f8e86e63c3b8cad74a03,SDY2011,study_file,SFL22037,200422_HIMC15_PICR_MDIPA_Subj_34518e80T1_debc.fcs,SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_Su...

In [ ]:
# https://docs.immport.org/apidocumentation/shareddataapi/studyfilepaths/


BASE_URL = 'https://www.immport.org/data/query/api/study/'
# endpoint = f"filePath/{target_study}"
endpoint = f"filePath/resultFiles/{target_study}"


r = immport_download.api(f"{BASE_URL}{endpoint}",token)
df = pd.read_json(r)
df.head()

/var/folders/s8/3jyy749s5dd02sr2jvqg53b40000gn/T/ipykernel_61701/967620679.py:11: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(r)

,fileDetailsId,generatedMD5,studyAccession,fileType,fileAccession,fileName,path
0,157951,fdab19398b3d52fe1264a8e2bd4d7349,SDY2011,result_file,916170,200422_HIMC15_PICR_MDIPA_Subj_089e98eaT1_debc....,SDY2011/ResultFiles/CyTOF_result/200422_HIMC15...
1,157952,c7d69e1ce380c8ea2e910fe02ed122f6,SDY2011,result_file,916182,200422_HIMC15_PICR_MDIPA_Subj_29703e49T1_debc....,SDY2011/ResultFiles/CyTOF_result/200422_HIMC15...
2,157953,9a663b6e05d60243931c580a87834fea,SDY2011,result_file,916183,200422_HIMC15_PICR_MDIPA_Subj_2d3ac920T1_debc....,SDY2011/ResultFiles/CyTOF_result/200422_HIMC15...
3,157954,277d725a6dd9ec71fd789c7c5d396b32,SDY2011,result_file,916189,200422_HIMC15_PICR_MDIPA_Subj_34518e80T1_debc....,SDY2011/ResultFiles/CyTOF_result/200422_HIMC15...
4,157955,b39b7ceff1ab43262fda250c546675f2,SDY2011,result_file,916205,200422_HIMC15_PICR_MDIPA_Subj_416ded86T1_debc....,SDY2011/ResultFiles/CyTOF_result/200422_HIMC15...

In [6]:
df.shape

(186, 7)

In [7]:
df.tail()

,fileDetailsId,generatedMD5,studyAccession,fileType,fileAccession,fileName,path
181,158132,6fd74113f0aa7f196e5040539ef74e1f,SDY2011,result_file,916259,200616_MDIPAa4_Subj_972d9455T1_debc.916259.fcs,SDY2011/ResultFiles/CyTOF_result/200616_MDIPAa...
182,158133,3545917a5e30afef26982e6c70070a9c,SDY2011,result_file,916292,200616_MDIPAa4_Subj_c06f90b7T1_debc.916292.fcs,SDY2011/ResultFiles/CyTOF_result/200616_MDIPAa...
183,158134,c8828137d45141bb5dcd00f3259258c4,SDY2011,result_file,916293,200616_MDIPAa4_Subj_c06f90b7T4_debc.916293.fcs,SDY2011/ResultFiles/CyTOF_result/200616_MDIPAa...
184,158135,074dc6c8dddae9e896f96120cc9f045b,SDY2011,result_file,916294,200616_MDIPAa4_Subj_c06f90b7T8_debc.916294.fcs,SDY2011/ResultFiles/CyTOF_result/200616_MDIPAa...
185,158136,7a185843801b84530fbe127a8bdd1a83,SDY2011,result_file,918293,Chen_MBAA_Results_1.918293.txt,SDY2011/ResultFiles/ImmPort_template/Chen_MBAA...

In [ ]:
# Download "filePath" : "SDY2011/ResultFiles/ImmPort_template/Chen_MBAA_Results_1.918293.txt"

immport_download.download_file(user_name,password,
    "SDY2011/ResultFiles/ImmPort_template/Chen_MBAA_Results_1.918293.txt", download_directory
)

Session Stop  (Error: Server aborted session: No such file or directory)

In [10]:


unique_file_paths = df.path.unique()
unique_txt_paths = [path for path in unique_file_paths if path.endswith(".txt")]

print(unique_txt_paths)

['SDY2011/ResultFiles/ImmPort_template/Chen_MBAA_Results_1.918293.txt']

In [11]:
immport_download.download_file(user_name,password, unique_txt_paths[0], download_directory)

Session Stop  (Error: Server aborted session: No such file or directory)

In [12]:
# See if we can find ResultFiles


url = f"https://www.immport.org/data/query/api/study/file/{target_study}"
r = immport_download.api(url, token)
df = pd.read_json(r)
df.head()

/var/folders/s8/3jyy749s5dd02sr2jvqg53b40000gn/T/ipykernel_61701/791997160.py:6: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(r)

,studyFileAccession,studyAccession,studyFileType,description,fileName,filePath
0,SFL22034,SDY2011,Study Data,CyTOF fcs,200422_HIMC15_PICR_MDIPA_Subj_089e98eaT1_debc.fcs,/SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_S...
1,SFL22035,SDY2011,Study Data,CyTOF fcs,200422_HIMC15_PICR_MDIPA_Subj_29703e49T1_debc.fcs,/SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_S...
2,SFL22036,SDY2011,Study Data,CyTOF fcs,200422_HIMC15_PICR_MDIPA_Subj_2d3ac920T1_debc.fcs,/SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_S...
3,SFL22037,SDY2011,Study Data,CyTOF fcs,200422_HIMC15_PICR_MDIPA_Subj_34518e80T1_debc.fcs,/SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_S...
4,SFL22038,SDY2011,Study Data,CyTOF fcs,200422_HIMC15_PICR_MDIPA_Subj_416ded86T1_debc.fcs,/SDY2011/StudyFiles/200422_HIMC15_PICR_MDIPA_S...

In [ ]:
print(df["studyFileType"].unique())

# Only Study Data

['Study Data']

In [21]:
# https://docs.immport.org/apidocumentation/shareddataapi/assayresults/


# url = f"https://api.immport.org/data/query/result/filePath?studyAccession={target_study}" # This one is from the tutorial
url = f"https://www.immport.org/data/query/result/filePath?studyAccession={target_study}"
url = f"https://www.immport.org/data/query/result/filePath?studyAccession={target_study}&experimentAccession=EXP34044" # CyTOF experiment
# url = f"https://www.immport.org/data/query/result/filePath?studyAccession={target_study}&experimentAccession=EXP34131" # Olink experiment



r = immport_download.api(url,token)
df = pd.read_json(r)
df.head()

/var/folders/s8/3jyy749s5dd02sr2jvqg53b40000gn/T/ipykernel_61701/3037734582.py:12: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(r)

,filePathId,fileInfoId,fileDetail,filesizeBytes,fileName,originalFileName,sourceType,sourceAccession,experimentAccession,measurementTechnique,...,strain,armAccession,armName,ageEvent,ageEventSpecify,ageUnit,maxSubjectAge,minSubjectAge,subjectPhenotype,filePath
0,916162_ES1674866_BS1227210,916162,CyTOF result,173358803,200604_PICR_MDIPAa4_C_Subj_03ca6bb0T1_MDIPAa4_...,200604_PICR_MDIPAa4_C_Subj_03ca6bb0T1_MDIPAa4_...,EXPSAMPLE,ES1674866,EXP34044,CyTOF,...,NaN,ARM6540,COVID positive,Age at enrollment,NaN,Years,89,18,NaN,/SDY2011/ResultFiles/CyTOF_result/200604_PICR_...
1,916163_ES1674867_BS1227211,916163,CyTOF result,101251246,200604_PICR_MDIPAa4_C_Subj_03ca6bb0T4_MDIPAa4_...,200604_PICR_MDIPAa4_C_Subj_03ca6bb0T4_MDIPAa4_...,EXPSAMPLE,ES1674867,EXP34044,CyTOF,...,NaN,ARM6540,COVID positive,Age at enrollment,NaN,Years,89,18,NaN,/SDY2011/ResultFiles/CyTOF_result/200604_PICR_...
2,916164_ES1674868_BS1227212,916164,CyTOF result,20113961,200529_HIMC15_MDIPAa4_Subj_05f57419T1_debc.916...,200529_HIMC15_MDIPAa4_Subj_05f57419T1_debc.fcs,EXPSAMPLE,ES1674868,EXP34044,CyTOF,...,NaN,ARM6540,COVID positive,Age at enrollment,NaN,Years,89,18,NaN,/SDY2011/ResultFiles/CyTOF_result/200529_HIMC1...
3,916165_ES1674869_BS1227213,916165,CyTOF result,57999091,200604_PICR_MDIPAa4_A_Subj_06f24a67T1_MDIPAa4_...,200604_PICR_MDIPAa4_A_Subj_06f24a67T1_MDIPAa4_...,EXPSAMPLE,ES1674869,EXP34044,CyTOF,...,NaN,ARM6540,COVID positive,Age at enrollment,NaN,Years,89,18,NaN,/SDY2011/ResultFiles/CyTOF_result/200604_PICR_...
4,916166_ES1674870_BS1227214,916166,CyTOF result,122689162,200604_PICR_MDIPAa4_A_Subj_06f24a67T12_MDIPAa4...,200604_PICR_MDIPAa4_A_Subj_06f24a67T12_MDIPAa4...,EXPSAMPLE,ES1674870,EXP34044,CyTOF,...,NaN,ARM6540,COVID positive,Age at enrollment,NaN,Years,89,18,NaN,/SDY2011/ResultFiles/CyTOF_result/200604_PICR_...

In [18]:
print(df["fileDetail"].unique())

# Only CyTOF results available in this query

['CyTOF result']

# Method 2: Download using the ImmPort File Download API

In [17]:
# https://www.immport.org/browser/?path=SDY2011&page=1

study_accession = "SDY2011"
target_file = "SDY2011-DR58_Tab.zip" # Found from ImmPort website


immport_download.download_file(user_name,password,
                                    f"{study_accession}/{target_file}",download_directory)

Completed: 4258K bytes transferred in 1 seconds
 (20279K bits/sec), in 1 file.

In `experiment.txt`:

EXPERIMENT_ACCESSION	DESCRIPTION	MEASUREMENT_TECHNIQUE	NAME	STUDY_ACCESSION	WORKSPACE_ID
EXP34044		CyTOF	Whole Blood CyTOF	SDY2011	6897
EXP34131		Olink assay	Serum Olink	SDY2011	6897